edge script is finnally working

diff --git a/Azure/ObjectClassificationByImage/modules/ObjectClassificationByImage/Dockerfile.arm32v7 b/Azure/ObjectClassificationByImage/modules/ObjectClassificationByImage/Dockerfile.arm32v7
--- a/Azure/ObjectClassificationByImage/modules/ObjectClassificationByImage/Dockerfile.arm32v7
+++ b/Azure/ObjectClassificationByImage/modules/ObjectClassificationByImage/Dockerfile.arm32v7
@@ -1,40 +1,41 @@
-FROM resin/raspberrypi3-debian:stretch
+FROM anirbandas/azureiotclientbase:stretch-1.55-1.40.0.stable
+ 
 
 WORKDIR /app
 
-RUN apt-get update && \
-    apt-get install -y --no-install-recommends libboost-python1.62.0 python3-pip libpython3-dev zip unzip python-setuptools
+RUN apt-get update && apt-get install -y python-numpy python-scipy && \
+    apt-get install -y libopenblas-dev || (echo "Failed to install libopenblas. Exiting..." && exit) && \
+    apt-get install -y liblapack-dev || (echo "Failed to install liblapack. Exiting..." && exit) && \
+    apt-get install -y python-opencv &&\
+    apt-get install zip unzip
 
-RUN pip3 install --upgrade pip 
-RUN pip install --upgrade setuptools 
-
-RUN apt-get install -y libopenblas-dev liblapack-dev
-
-COPY requirements.txt ./
-RUN pip install -r requirements.txt
-
-RUN apt-get update && \
-    apt-get install -y --no-install-recommends python-opencv
-
-COPY . .
-
+# Install Mxnet
 COPY ./mxnet-python.tar.gz .
 
-RUN pip install wheel && \
-    tar xzf mxnet-python.tar.gz && \
+RUN apt-get update && \
+    apt-get install -y python-setuptools &&\
+    pip install wheel && \
+    tar xzf mxnet-python.tar.gz || (echo "Unable to untar mxnet python module. Exiting..." && exit) && \
     mv python/dist/mxnet-0.11.0-py2.7.egg mxnet.zip && \
-    unzip -q mxnet.zip && \
+    unzip -q mxnet.zip|| (echo "Unable to unzip mxnet dist. Exiting..." && exit) && \
     rm -f mxnet.zip && \
     ln -sf `pwd`/mxnet/libmxnet.so python/mxnet/libmxnet.so &&\
     cd python && \
-    python setup.py install && \
+    python setup.py install || (echo "Unable to install MXNET! Stopping verification..." && exit) && \
     cd ../ && \
     rm -rf tmp/ && \
     rm -rf tests/ && \
     rm -rf python/ && \
     rm -rf EGG-INFO/ 
 
+# Copy rest of the folder
+COPY . .
+
+RUN chmod -R 777 .
+
 RUN useradd -ms /bin/bash moduleuser
 USER moduleuser
 
-ENTRYPOINT [ "python3", "-u", "./main_on_demand.py" ]
+# Entry point with unbuffered python stdout
+ENTRYPOINT [ "python", "-u", "./main_on_demand.py" ]
+
